CREATE SCHEMA IF NOT EXISTS CARS;
CREATE TABLE CARS.PERSON
  (
    ID long PRIMARY KEY NOT NULL,
    NAME VARCHAR(45),
    BIRTHDATE date
    );
CREATE TABLE CARS.CAR
    (
    ID LONG PRIMARY KEY NOT NULL,
    MODEL VARCHAR(45),
    HORSEPOWER int NOT NULL,
    OWNER LONG NOT NULL,
    CONSTRAINT CAR_PERSON_ID_fk FOREIGN KEY (OWNER) REFERENCES PERSON (ID) ON DELETE CASCADE ON UPDATE CASCADE
  );
